### ISSUE TITLE
No install Garmin 245

### ISSUE THREAD

**Issue by Delmar171** [forsb/Ticker#2]
Hey left a review. App was perfect. Then mysteriously disappeared from watch. Can’t reinstall. Says on app it is, but then just goes back to install button. 
Would love this to work, any help appreciated.

**Comment by filarl** [comment]
Thanks for your feedback. I'm afriad this is a Garmin issue, not related to this app. Try contacting them instead.

Anyway, when you report a bug, please state which watch you are using and if possible its softeware version, otherwise it's impossible to troubleshoot.
